[project]
name = "image-search"
version = "1.0.0"
description = "Image-search is an image search engine based on CLIP model."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.42.75",
    "fastapi>=0.135.2",
    "pillow>=12.1.1",
    "python-dotenv>=1.2.2",
    "torch>=2.11.0",
    "torchvision>=0.26.0",
    "transformers>=5.3.0",
    "uvicorn>=0.42.0",
]
